[package]
name = "slint-text-rendering-artifact-demo"
version = "0.1.0"
edition = "2021"
build = "build.rs"
repository = "https://github.com/kkettinger/slint-text-rendering-artifact-demo.git"

[dependencies]
slint = "1.0.2"

[build-dependencies]
slint-build = "1.0.0"
