import { Button , Slider} from "std-widgets.slint";

export component AppWindow inherits Window {

    width: 800px;
    height: 480px;

    VerticalLayout {
        alignment: LayoutAlignment.center;
        spacing: 20px;
        padding: 20px;

        Text {
            text: "Hello World 123";
            font-size: slider.value * 1px;
        }

        slider := Slider {
            height: 40px;
            minimum: 8;
            value: 20;
        }
    }
}
